version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sammy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./internal
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./internal/.env
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
